### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by tharanp** [IMAmuseum/OSCI-Toolkit-Installer#5]
Hi there,

there seems to be error in the installer. We did the following steps and we’re getting error msg. see attachments:

-We did the fresh new Drupal 7.43 install
-dropped all the installer files from zip to the root.
-Ran osci-install.php
-inputted our appropriate server/database info
-it says page not found at the ’osci-seeder.php’

Documentation is a bit unclear so we’re kind of lost what might be causing the issue.  We can go ahead and install the modules independently but it would be good to have the dummy content as well so we can understand how OSCI functionality.

Please let us know 

Thanks

**Comment by jeremytubbs** [comment]
Hello,

From what I can surmise from your list of operations, you do not need to install Drupal before you run the OSCI installer.  The installer handles the Drupal installation for you.

Thanks

**Comment by tharanp** [comment]
Thanks,

the installtion worked but we're faced with another error when trying to access the site. Error:

PDOException: SQLSTATE[28000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) in drupal_get_installed_schema_version() (line 155 of /var/www/vhosts/site-url.com/httpdocs/osci4/includes/install.inc).
The website encountered an unexpected error. Please try again later.

We do see the database has been created on our server.

**Comment by jeremytubbs** [comment]
What does line 222 of your `/sites/default/settings.php` look like?  
What mysql username did you enter for the installer? 
How many database tables where created?

**Comment by tharanp** [comment]
Ok we got passed that error and we have access to Drupal but we're hit with another error:

Notice: Undefined index: module in FieldInfo->prepareInstanceWidget() (line 591 of /var/www/vhosts/site-url.com/httpdocs/osci5/modules/field/field.info.class.inc).
Notice: Undefined index: module in FieldInfo->prepareInstanceDisplay() (line 626 of /var/www/vhosts/site-url.com/httpdocs/osci5/modules/field/field.info.class.inc).
Notice: Undefined index: module in FieldInfo->prepareInstanceDisplay() (line 626 of /var/www/vhosts/site-url.com/httpdocs/osci5/modules/field/field.info.class.inc).
Notice: Undefined index: module in FieldInfo->prepareInstanceWidget() (line 591 of /var/www/vhosts/site-url.com/httpdocs/osci5/modules/field/field.info.class.inc).
Notice: Undefined index: module in FieldInfo->prepareInstanceDisplay() (line 626 of /var/www/vhosts/site-url.com/httpdocs/osci5/modules/field/field.info.class.inc).

**Comment by TyeNoobDev** [comment]
I'm also getting the same error in a localhost xamp enviroment

**Comment by jeremytubbs** [comment]
I cannot reproduce this error but I found this thread in the Drupal forum that may help - https://www.drupal.org/node/2401287
